@startuml
title Pathobefund (Vorher): Probenweise Grouper-Struktur

skinparam linetype ortho

package "DiagnosticReport" {
  object "DiagnosticReport" as Report
}

package "Specimens" {
  object "Specimen Sample" as Sample #FFCCCC
  object "Specimen Schnitt 1" as Schnitt1 #FFCCCC
  object "Specimen Schnitt 2" as Schnitt2 #FFCCCC
}

package "PathoFindings"{
  object "PathoFinding A1" as A1 #LightBlue
  object "PathoFinding A2" as A2 #LightBlue
  object "PathoFinding A3" as A3 #LightBlue
  object "PathoFinding B1" as B1 #LightBlue
  object "PathoFinding B2" as B2 #LightBlue
  object "PathoFinding B3" as B3 #LightBlue
  object "PathoFinding C1" as C1 #LightBlue
  object "PathoFinding C2" as C2 #LightBlue
  object "PathoFinding C3" as C3 #LightBlue
}

package "Grouperinstanzen" {
  object "Makro A" as MakroA #CFF5CF
  object "Makro B" as MakroB #CFF5CF
  object "Makro C" as MakroC #CFF5CF
  object "Mikro A" as MikroA #CFF5CF
  object "Mikro B" as MikroB #CFF5CF
  object "Mikro C" as MikroC #CFF5CF
  object "DiagnosticConclusion A" as ConclusionA #CFF5CF
  object "DiagnosticConclusion B" as ConclusionB #CFF5CF

}

' Verbindungen
Report --> MakroA : result
Report --> MakroB
Report --> MakroC
Report --> MikroA
Report --> MikroB
Report --> MikroC
Report --> ConclusionA
Report --> ConclusionB

MakroA --> A1 : .hasMember
MakroB --> B1
MikroC --> C1

MakroA --> A2
MakroB --> B2
MikroC --> C2

ConclusionA --> A3
ConclusionA --> B3
ConclusionB --> C3

A1 --> Sample : specimen
A2 --> Schnitt1

B1 --> Sample
B2 --> Schnitt1

C1 --> Sample
C2 --> Schnitt2


MakroA --> Sample : specimen
MakroA --> Schnitt1

MakroB --> Sample
MakroB --> Schnitt1

MikroC --> Sample
MikroC --> Schnitt2

ConclusionA --> Sample : specimen
ConclusionB --> Sample : specimen

@enduml
